# Tratamento dos Dados 🪢

## Sumário da Aula

<ul>
    <li>Aspectos de Tratamento dos Dados 🪢</li>
    <li>Junção, Mescla e Concatenação 🥇</li>
    <li>Pivoteamento 🥈</li>
</ul>

### Biblioteca Principal 📚: pandas

<img src="https://pandas.pydata.org/docs/_static/pandas.svg" width="100" style="float: right;">

In [1]:
import pandas as pd

## Aspectos de Tratamento dos Dados 🪢

### Indexação Hierárquica

<ul>
    <li>Dados podem estar espalhados em distintas fontes de dados; ou dispostos em formatos pouco fáceis de analisar</li>
    <li>Para contornar esta dificuldade, vamos fazer uso da indexação hierárquica para:
        <ul>
            <li>habilitar o uso de dois ou mais níveis de índice para cada eixo; e</li>
            <li>permitir trabalhar com dados em dimensão superior a 2 ainda que disposto em formato bidimensional.</li>
</ul>

<pre><img src="figs/2d-shot-table.png" width="250px" style="margin-left: auto; margin-right: auto;"><img src="figs/3d-shot-cube.png" width="200px" style="margin-left: auto; margin-right: auto;"><img src="figs/2d-shot-cube.png" width="200px" style="margin-left: auto; margin-right: auto;"></pre>

👉 Referência: <a href='https://pandas.pydata.org/'>pandas.pydata.org</a>

👉 Pandas <a href='https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf'>cheat sheet</a>

#### Indexação Hierárquica em Series 🎞️

<pre>Você pode ter índice hierárquico em Series -- nas linhas, naturalmente</pre>

In [2]:
from random import sample
data = pd.Series(sample(range(30), 9),
                 index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1    15
   2    28
   3    29
b  1     0
   3    18
c  1    19
   2     9
d  2    20
   3    12
dtype: int64

In [3]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

<pre>Você pode acessar elementos específicos do primeiro nível hierárquico...</pre>

In [4]:
data.loc['b']

1     0
3    18
dtype: int64

In [5]:
data.loc[['b', 'd']]

b  1     0
   3    18
d  2    20
   3    12
dtype: int64

<pre>..., bem como elementos específicos do segundo nível hierárquico.</pre>

In [6]:
data.loc[['b', 'd'], [1,2,3]]

b  1     0
   3    18
d  2    20
   3    12
dtype: int64

<pre>Você pode "desempilhar" um nível do índice hierárquico e o colocar como colunas em um DataFrame 📽️</pre>

In [7]:
data = data.unstack()
data

      1     2     3
a  15.0  28.0  29.0
b   0.0   NaN  18.0
c  19.0   9.0   NaN
d   NaN  20.0  12.0

<pre>Você pode "empilhar" as colunas e as colocar como um nível do índice hierárquico</pre>

In [8]:
data = data.stack()
data

a  1    15.0
   2    28.0
   3    29.0
b  1     0.0
   3    18.0
c  1    19.0
   2     9.0
d  2    20.0
   3    12.0
dtype: float64

#### Indexação Hierárquica em DataFrame 📽️

<pre>Você pode ter índice hierárquico tanto em linhas <u>quanto em colunas</u></pre>

In [9]:
frame = pd.DataFrame([[0, 1, 2],[3, 4, 5],[6, 7, 8],[9, 10, 11]],
                     index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
                     columns=[["Ohio", "Ohio", "Colorado"], 
                              ["Green", "Red", "Green"]])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

<pre>Você pode atribuir nomes aos índices hierárquicos das linhas e das colunas</pre>

In [10]:
frame.index.names = ["key1", "key2"]
frame.columns.names = ["state", "color"]
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

<pre>Você pode contar os níveis dos índices hierárquicos das linhas e das colunas</pre>

In [11]:
frame.index.nlevels, frame.columns.nlevels

(2, 2)

<pre>Você pode acessar elementos específicos do primeiro nível do índice hierárquico das linhas...</pre>

In [12]:
frame.loc['a']

state  Ohio     Colorado
color Green Red    Green
key2
1         0   1        2
2         3   4        5

<pre>..., bem como elementos específicos do primeiro nível do índice hierárquico das colunas</pre>

In [13]:
frame.loc[['a'],['Ohio']]

state      Ohio
color     Green Red
key1 key2
a    1        0   1
     2        3   4

#### Reorganização e Ordenação dos Níveis da Indexação Hierárquica

In [14]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

<pre>Você pode reorganizar os níveis do índice hierárquico das linhas...</pre>

In [15]:
frame = frame.swaplevel("key1", "key2")
frame

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

<pre>..., bem como ordenar lexicograficamente todos os níveis do índice hierárquico das linhas,</pre>

In [16]:
frame.sort_index()

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

<pre>... ou ordenar lexicograficamente apenas um nível específico do índice hierárquico das linhas.</pre>

In [17]:
frame.sort_index(level=1, ascending=False)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
2    b        9  10       11
1    b        6   7        8
2    a        3   4        5
1    a        0   1        2

<pre>🍒 🎂 Você pode também reorganizar ou ordenar lexicograficamente os níveis do índice hierárquico das colunas</pre>

In [18]:
frame.swaplevel("state", "color", axis='columns')

color     Green  Red    Green
state      Ohio Ohio Colorado
key2 key1
1    a        0    1        2
2    a        3    4        5
1    b        6    7        8
2    b        9   10       11

In [19]:
frame.sort_index(axis='columns')

state     Colorado  Ohio
color        Green Green Red
key2 key1
1    a           2     0   1
2    a           5     3   4
1    b           8     6   7
2    b          11     9  10

In [20]:
frame.sort_index(axis='columns', level=1, ascending=False)

state     Ohio       Colorado
color      Red Green    Green
key2 key1
1    a       1     0        2
2    a       4     3        5
1    b       7     6        8
2    b      10     9       11

#### Indexando com algumas colunas de um DataFrame

<pre>Lembra que você pode "empilhar" as colunas e as colocar como um nível do índice hierárquico?</pre>

<pre>Você pode também transformar um conjunto de 'n' colunas em 'n' níveis hierárquicos...</pre>

In [21]:
frame = pd.DataFrame({"a": range(7),
                      "b": range(7, 0, -1),
                      "c": ["one", "one", "one", 
                            "two", "two", "two", "two"],
                      "d": [0, 1, 2, 0, 1, 2, 3]})
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [22]:
frame = frame.set_index(["c", "d"])
frame

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

<pre>... e transformar 'n' níveis hierárquicos em um conjunto de 'n'</pre>

In [23]:
frame = frame.reset_index()
frame

     c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

## Junção, Mescla e Concatenação 🥇

Os dados de objetos pandas podem ser combinados conforme as operações a seguir.

<table>
    <tr><th>Opção</th><th>Descrição</th></tr>
    <tr><td>pandas.merge</td><td>Conecta linhas em DataFrames com base em uma ou mais chaves. Essa operação será conhecida dos usuários de SQL ou de outros bancos de dados relacionais, pois ela implementa as operações de junção (join) dos bancos de dados</td></tr>
    <tr><td>pandas.concat</td><td>Concatena ou "empilha" objetos ao longo de um eixo</td></tr>
</table>

### Junção

In [24]:
infectados = pd.DataFrame([['ce', 'fortaleza', 10, 1], \
                           ['rj', 'rio de janeiro', 20, 2], \
                           ['df', 'brasília', 30, 3]], \
                          columns=['estado', 'municipio', 
                                   'casos', 'óbitos'])

vacinados = pd.DataFrame([['ce', 'fortaleza', 100], \
                          ['rj', 'rio de janeiro', 200], \
                          ['rn', 'natal', 300]], \
                         columns=['estado', 'municipio', 
                                  'habitantes vacinados'])

#### Inner Join

<pre>Inner join utiliza somente as combinacões de chaves observadas nas duas tabelas sendo combinadas</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Inner Join</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                  <td bgcolor='orange'>100.0</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [25]:
pd.merge(infectados, vacinados, how='inner')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza     10       1                   100
1     rj  rio de janeiro     20       2                   200

#### Left Outer Join

<pre>Left Outer Join utiliza todas as combinacões de chaves encontradas na tabela à esquerda</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Left Outer Join</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                  <td bgcolor='orange'>100.0</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                  <td bgcolor='gray'>NaN</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [26]:
pd.merge(infectados, vacinados, how='left')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza     10       1                 100.0
1     rj  rio de janeiro     20       2                 200.0
2     df        brasília     30       3                   NaN

#### Right Outer Join

<pre>Right Outer Join utiliza todas as combinacões de chaves encontradas na tabela à direita</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Left Outer Join</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10.0</td>
                  <td bgcolor='yellow'>1.0</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20.0</td>
                  <td bgcolor='yellow'>2.0</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [27]:
pd.merge(infectados, vacinados, how='right')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza   10.0     1.0                   100
1     rj  rio de janeiro   20.0     2.0                   200
2     rn           natal    NaN     NaN                   300

#### Outer Join

<pre>Outer Join utiliza todas as combinacões de chaves observadas nas duas tabelas em conjunto</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Outer Join</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20.0</td>
                  <td bgcolor='yellow'>2.0</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasilia</td>
                  <td bgcolor='gray'>30.0</td>
                  <td bgcolor='gray'>3.0</td>
                  <td bgcolor='gray'>NaN</td>
                </tr>
                <tr>
                  <th>3</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>300.0</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [28]:
pd.merge(infectados, vacinados, how='outer')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza   10.0     1.0                 100.0
1     df        brasília   30.0     3.0                   NaN
2     rj  rio de janeiro   20.0     2.0                 200.0
3     rn           natal    NaN     NaN                 300.0

#### Quadro-resumo das opções de junção

<table>
    <tr><th>Opção</th><th>Comportamento</th></tr>
    <tr><td>how='inner'</td><td>Utiliza somente as combinacões de chaves observadas nas duas tabelas sendo combinadas</td></tr>
    <tr><td>how='left'</td><td>Utiliza todas as combinacões de chaves encontradas na tabela à esquerda</td></tr>
    <tr><td>how='right'</td><td>Utiliza todas as combinacões de chaves encontradas na tabela à direita</td></tr>
    <tr><td>how='outer'</td><td>Utiliza todas as combinacões de chaves observadas nas duas tabelas em conjunto</td></tr>
</table>

<img src='figs/outer-join.gif' width='600px' style='margin-left: auto; margin-right: auto;'>

👉 dica: a(s) chave(s) pode(m) ser inferida(s) a partir do contexto da interseção entre as tabelas, mas também pode(m) ser especificada(s) com o parâmetro <i>on</i>

### Mescla

In [29]:
pd.merge(infectados, vacinados, 
         on=['estado', 'municipio'], how='inner')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza     10       1                   100
1     rj  rio de janeiro     20       2                   200

👉 mais dica: caso a(s) chave(s) não possa(m) ser inferida(s), com nomes diferentes de coluna, deve-se especificá-la(s) com os parâmetros <i>left_on</i> e <i>right_on</i>

In [30]:
pd.merge(infectados, vacinados, left_on=['estado', 'municipio'], 
         right_on=['estado', 'municipio'],  how='inner')

  estado       municipio  casos  óbitos  habitantes vacinados
0     ce       fortaleza     10       1                   100
1     rj  rio de janeiro     20       2                   200

<pre>🍒 🎂 Você pode também combinar duas tabelas com a operação de junção na presença de índice hierárquico (<i>join</i>)</pre>

In [31]:
infectados = infectados.set_index(['estado', 'municipio'])
infectados

                       casos  óbitos
estado municipio
ce     fortaleza          10       1
rj     rio de janeiro     20       2
df     brasília           30       3

In [32]:
vacinados = vacinados.set_index(['estado', 'municipio'])
vacinados

                       habitantes vacinados
estado municipio
ce     fortaleza                        100
rj     rio de janeiro                   200
rn     natal                            300

In [33]:
infectados.join(vacinados, how='inner')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza          10       1                   100
rj     rio de janeiro     20       2                   200

In [34]:
infectados.join(vacinados, how='left')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza          10       1                 100.0
rj     rio de janeiro     20       2                 200.0
df     brasília           30       3                   NaN

In [35]:
infectados.join(vacinados, how='right')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza        10.0     1.0                   100
rj     rio de janeiro   20.0     2.0                   200
rn     natal             NaN     NaN                   300

In [36]:
infectados.join(vacinados, how='outer')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza        10.0     1.0                 100.0
df     brasília         30.0     3.0                   NaN
rj     rio de janeiro   20.0     2.0                 200.0
rn     natal             NaN     NaN                 300.0

### Concatenação

<pre>Você pode empilhar ao longo das linhas com uma tabela em cima da outra (alinhando os índices das colunas)...</pre>

<table>
    <tr><th>Tabelas Acima e Abaixo</th><th>Tabelas Concatenadas</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
            <br />
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10.0</td>
                  <td bgcolor='yellow'>1.0</td>
                  <td>NaN</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20.0</td>
                  <td bgcolor='yellow'>2.0</td>
                  <td>NaN</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasilia</td>
                  <td bgcolor='gray'>30.0</td>
                  <td bgcolor='gray'>3.0</td>
                  <td>NaN</td>
                </tr>
                <tr>
                  <th>3</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td>NaN</td>
                  <td>NaN</td>
                  <td bgcolor='orange'>100.0</td>
                </tr>
                <tr>
                  <th>4</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td>NaN</td>
                  <td>NaN</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
                <tr>
                  <th>5</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td>NaN</td>
                  <td>NaN</td>
                  <td bgcolor='pink'>300.0</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [37]:
pd.concat([infectados, vacinados], axis='index')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza        10.0     1.0                   NaN
rj     rio de janeiro   20.0     2.0                   NaN
df     brasília         30.0     3.0                   NaN
ce     fortaleza         NaN     NaN                 100.0
rj     rio de janeiro    NaN     NaN                 200.0
rn     natal             NaN     NaN                 300.0

<pre>... bem como pode ao longo das colunas com uma tabela após a outra (alinhando os índices das linhas)...</pre>

<table>
    <tr><th>Tabela à Esquerda</th><th>Tabela à Direita</th><th>Tabelas Concatenadas</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10</td>
                  <td bgcolor='yellow'>1</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20</td>
                  <td bgcolor='yellow'>2</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasília</td>
                  <td bgcolor='gray'>30</td>
                  <td bgcolor='gray'>3</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='orange'>100</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='orange'>200</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>300</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td bgcolor='green'>ce</td>
                  <td bgcolor='green'>fortaleza</td>
                  <td bgcolor='yellow'>10.0</td>
                  <td bgcolor='yellow'>1.0</td>
                  <td bgcolor='orange'>100.0</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td bgcolor='green'>rj</td>
                  <td bgcolor='green'>rio de janeiro</td>
                  <td bgcolor='yellow'>20.0</td>
                  <td bgcolor='yellow'>2.0</td>
                  <td bgcolor='orange'>200.0</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td bgcolor='gray'>df</td>
                  <td bgcolor='gray'>brasilia</td>
                  <td bgcolor='gray'>30.0</td>
                  <td bgcolor='gray'>3.0</td>
                  <td bgcolor='gray'>NaN</td>
                </tr>
                <tr>
                  <th>3</th>
                  <td bgcolor='pink'>rn</td>
                  <td bgcolor='pink'>natal</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>NaN</td>
                  <td bgcolor='pink'>300.0</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

In [38]:
pd.concat([infectados, vacinados], axis='columns')

                       casos  óbitos  habitantes vacinados
estado municipio
ce     fortaleza        10.0     1.0                 100.0
rj     rio de janeiro   20.0     2.0                 200.0
df     brasília         30.0     3.0                   NaN
rn     natal             NaN     NaN                 300.0

## Pivoteamento 🥈

<table>
    <tr><th>Formato Longo é Melhor para Armazenar</th><th>Formato Largo é Melhor para Analisar</th></tr>
    <tr>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th></th>
                  <th></th>
                  <th>variável</th>
                  <th>valor</th>
                </tr>
                <tr>
                  <th>0</th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>1</th>
                  <td>ce</td>
                  <td>fortaleza</td>
                  <td>casos</td>
                  <td>10.0</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td>rj</td>
                  <td>rio de janeiro</td>
                  <td>óbitos</td>
                  <td>2.0</td>
                </tr>
                <tr>
                  <th>3</th>
                  <td>df</td>
                  <td>brasília</td>
                  <td>óbitos</td>
                  <td>3.0</td>
                </tr>
                <tr>
                  <th>4</th>
                  <td>rn</td>
                  <td>natal</td>
                  <td>habitantes vacinados</td>
                  <td>300.0</td>
                </tr>
              </tbody>
            </table>
        </td>
        <td>
            <table border="1">
              <thead>
                <tr>
                  <th></th>
                  <th>estado</th>
                  <th>municipio</th>
                  <th>casos</th>
                  <th>óbitos</th>
                  <th>habitantes vacinados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th>0</th>
                  <td>ce</td>
                  <td>fortaleza</td>
                  <td>10.0</td>
                  <td>NaN</td>
                  <td>NaN</td>
                </tr>
                <tr>
                  <th>1</th>
                  <td>rj</td>
                  <td>rio de janeiro</td>
                  <td>NaN</td>
                  <td>2.0</td>
                  <td>NaN</td>
                </tr>
                <tr>
                  <th>2</th>
                  <td>df</td>
                  <td>brasilia</td>
                  <td>NaN</td>
                  <td>3.0</td>
                  <td>NaN</td>
                </tr>
                <tr>
                  <th>3</th>
                  <td>rn</td>
                  <td>natal</td>
                  <td>NaN</td>
                  <td>NaN</td>
                  <td>300.0</td>
                </tr>
              </tbody>
            </table>
        </td>
    </tr>
</table>

👉 dica: pivotear é uma palavra difícil, correto? Vamos simplificar.
<ul>
    <li>formato longo: tem muitas linhas para designar uma linha por atributo;</li>
    <li>formato largo: tem muitas colunas para designar uma coluna por atributo.</li>
</ul>

Dito isto, pivoteamento de formato longo em formato largo se faz <i>transformando linhas em colunas</i>;

Simetricamente, pivoteamento de formato largo em formato longo se faz <i>transformando colunas em linhas</i>.

### Pivoteamento do Formato Longo em Formato Largo

👉 dica: lembre-se que o pivoteamento de formato longo em formato largo se dá transformando linhas em colunas

In [39]:
formato_longo = pd.DataFrame([['ce', 'fortaleza', 'casos', 10.0],
                              ['rj', 'rio de janeiro', 'óbitos', 2.0],
                              ['df', 'brasília', 'óbitos', 3.0],
                              ['rn', 'natal', 
                               'habitantes vacinados', 300.0]],
                             columns=['estado', 'municipio', 
                                      'variável', 'valor'])

In [40]:
formato_longo

  estado       municipio              variável  valor
0     ce       fortaleza                 casos   10.0
1     rj  rio de janeiro                óbitos    2.0
2     df        brasília                óbitos    3.0
3     rn           natal  habitantes vacinados  300.0

In [41]:
formato_longo.pivot(index=['estado', 'municipio'], 
                    columns='variável', values='valor')

variável               casos  habitantes vacinados  óbitos
estado municipio
ce     fortaleza        10.0                   NaN     NaN
df     brasília          NaN                   NaN     3.0
rj     rio de janeiro    NaN                   NaN     2.0
rn     natal             NaN                 300.0     NaN

### Pivoteamento do Formato Largo em Formato Longo

👉 dica: lembre-se que o pivoteamento de formato largo em formato longo se dá transformando colunas em linhas

In [42]:
formato_largo = pd.DataFrame([['ce', 'fortaleza', 10.0, None, None],
                              ['df', 'brasília', None, None, 3.0],
                              ['rj', 'rio de janeiro', 
                               None, None, 2.0],
                              ['rn', 'natal', None, 300.0, None]],
                             columns=['estado', 'municipio', 
                                      'casos', 'habitantes vacinados', 
                                      'óbitos'])

In [43]:
formato_largo

  estado       municipio  casos  habitantes vacinados  óbitos
0     ce       fortaleza   10.0                   NaN     NaN
1     df        brasília    NaN                   NaN     3.0
2     rj  rio de janeiro    NaN                   NaN     2.0
3     rn           natal    NaN                 300.0     NaN

In [44]:
formato_largo.melt(id_vars=['estado', 'municipio'], 
                   var_name='variável', 
                   value_name='valor').dropna()

   estado       municipio              variável  valor
0      ce       fortaleza                 casos   10.0
7      rn           natal  habitantes vacinados  300.0
9      df        brasília                óbitos    3.0
10     rj  rio de janeiro                óbitos    2.0

<font size=7><center><code>Executem todo este caderno...</code></center></font>