# Limpeza e Preparação dos Dados 🏗️ 🎲

<pre>Utilizaremos, nessa aula, uma base de dados sintética, inspirada na base de dados da aula anterior, para fins didáticos.</pre>

In [1]:
!pip install --upgrade pandas --quiet

In [2]:
import pandas as pd

df_inativos = pd.read_json('data/df_inativos_sintetica.json')
df_inativos.head()

,Ano,OrgN1,OrgN2,Valor
0,2015,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,540948943
1,2016,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,567996390.2
2,2017,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,AUSENTE
3,2018,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,626216020.1
4,2019,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,657526821.1

## Limpeza 🧹 dos Dados 🎲

<pre>O trabalho do cientista de dados é feito, muitas vezes, em bases de dados fornecidas por terceiros, em que não há garantia de consistência e completude.</pre>

### Eliminando Dados Duplicados

<pre>A presença de dados duplicados ou incompletos pode prejudicar o resultado da análise realizada.</pre>

<pre>Portanto, é necessário fazer certas verificações preliminares.</pre>

<pre>Inicie listando as linhas duplicadas no DataFrame <b>df_inativos</b>.</pre>

👉 dica: utilize o método `duplicated` do DataFrame como indexação booleana do DataFrame `df_inativos`.

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos[df_inativos.duplicated()]
```

<br/>

</details>

<pre>Agora, atualize o DataFrame <b>df_inativos</b>, removendo as linhas duplicadas.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos = df_inativos.drop_duplicates()
```

<br/>

</details>

<pre>Repita a listagem das linhas duplicadas para ter certeza que não há mais linhas em multiplicidade.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos[df_inativos.duplicated()]
```

<br/>

</details>

### Dados Ausentes

<pre>Liste, se existirem, as linhas que têm valores nulos (<b>na</b>) na coluna <b>Valor</b> do DataFrame <b>df_inativos</b>.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos[df_inativos['Valor'].isna()]
```

<br/>

</details>

<pre>Agora, liste todos os valores distintos da coluna <b>Valor</b> do DataFrame <b>df_inativos</b>.</pre>

👉 dica: para listar os valores únicos de uma coluna, basta utilizar o método `unique` na `Series` desejada.

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos['Valor'].unique()
```

<br/>

</details>

#### Substituindo Valores

🚨 Observe que temos valor que não é número, tratando-se de dado ausente (<i>literalmente</i>). 🚨

<pre>Para uniformizar nossa base de dados, vamos substituir os valores identificados como <b>AUSENTE</b> na coluna <b>Valor</b> para o tipo de dados <b>None</b>, armazenando o resultado no DataFrame <b>df_inativo</b>.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos['Valor'] = df_inativos['Valor'].replace('AUSENTE', None)
```

<br/>

</details>

<pre>Verifique, por meio do atributo <b>dtypes</b> do DataFrame, o tipo de dados da coluna <b>Valor</b>.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos.dtypes
```

<br/>

</details>

🚨 Note que o tipo de dados da coluna <b>Valor</b> é <b>object</b>, uma vez que havia ocorrências de <b>'AUSENTE'</b>. 🚨

<pre>Para que a coluna <b>Valor</b> agora tenha o tipo de dados apropriado, utilize o método <b>astype</b> para converter o tipo de dados da coluna <b>Valor</b> para <b>float</b>. Lembre-se de armazenar o resultado no DataFrame <b>df_inativos</b>.</pre>

👉 dica: veja a documentação do <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.astype.html">astype</a>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos['Valor'] = df_inativos['Valor'].astype(float)
```

<br/>

</details>

<pre>Verifique novamente os tipos de dados das colunas do DataFrame <b>df_inativos</b> e certifique-se que o tipo de dados da coluna <b>Valor</b> passou a ser <b>float</b>.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos.dtypes
```

<br/>

</details>

#### Preenchendo Dados Ausentes

<pre>Agora, vamos falar das possíveis estratégias para tratar dados ausentes.</pre>

<pre>A melhor solução, nem sempre viável, é solicitar ao responsável pela disponibilização da base de dados que apresente os dados completos.</pre>

<pre>Caso isso não seja possível ou caso os valores estejam ausentes na base original, pode ser inevitável que haja alguma imprecisão na análise.</pre>

<pre>Dependendo do contexto, pode ser aceitável imputar valores aos dados ausentes e isso pode ser feito por diversos métodos.</pre>

<pre>Vamos ilustrá-los nos dados referentes à <b>AGENCIA NACIONAL DE SAUDE SUPLEMENTAR</b>. Portanto, execute a célula abaixo.</pre>

In [3]:
df_inativos_ans = df_inativos[df_inativos["OrgN2"] == "AGENCIA NACIONAL DE SAUDE SUPLEMENTAR"].copy()
df_inativos_ans

,Ano,OrgN1,OrgN2,Valor
0,2015,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,540948943
1,2016,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,567996390.2
2,2017,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,AUSENTE
3,2018,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,626216020.1
4,2019,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,657526821.1
5,2020,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,690403162.2
6,2021,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,None
21,2019,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,657526821.1

<pre>A partir de agora, vamos ilustrar três exemplos de métodos para imputar valores aos dados ausentes. Trata-se de lista exemplificativa.</pre>

<pre>    1 - Utilize o método <b>fillna</b> (do DataFrame <b>df_inativos_ans</b>) para substituir os valores ausentes (<b>None</b>) por <b>0</b>;</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos_ans[['Valor']].fillna(0)
```

<br/>

</details>

<pre>    2 - Alternativamente, utilize o valor da linha anterior para preencher os valores ausentes, com o método <b>ffill</b> do DataFrame <b>df_inativos_ans</b>;</pre>

🚨 Similarmente, você pode utilizar o valor da linha posterior para preencher os valores ausentes, utilizando o método <b>bfill</b>. 🚨

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos_ans[['Valor']].ffill()
```

<br/>

</details>

<pre>    3 - Por fim, utilize valores existentes para calcular um valor intermediário, com o método <b>interpolate</b> do DataFrame <b>df_inativos_ans</b>.</pre>

👉 dica: consulte a documentação do <a href='https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.interpolate.html'>interpolate</a>.

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos_ans[['Valor']].interpolate()
```

<br/>

</details>

<pre>Note que cada um dos métodos propostos resultará em valores distintos que podem não guardar relação com os valores reais.</pre>

<pre>A imputação de valores, se realizada, deve ser documentada e explicitada quando da apresentação do resultado da análise de dados.</pre>

🚨 Perceba que não armazenamos o valor imputado no DataFrame <b>df_inativos</b>, até porque utilizamos uma cópia do DataFrame (veja acima que usamos o método <b>copy</b>) 🚨

<pre>Portanto, aplique a interpolação (ou qualquer método de sua preferência) na coluna <b>Valor</b> do DataFrame <b>df_inativos</b>, lembrando de armazenar o resultado na mesma variável.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos['Valor'] = df_inativos['Valor'].interpolate()
```

<br/>

</details>

## Transformação 🛠️ dos Dados 🎲

### Discretizando e Compartimentalizando (<i>Bin</i>)

<pre>Considerando os valores dos anos presentes na base, crie uma coluna <b>Década</b> no DataFrame <b>df_inativos</b>, indicando a faixa da década referente ao dado <b>Ano</b>.</pre>

<pre>Exemplos:
    - se o ano for <b>2015</b>, a década é <b>2010</b>; 
    - se o ano for <b>2020</b>, a década é <b>2020</b>; 
    - se o ano for <b>2021</b>, a década é <b>2020</b>.</pre>

👉 dica: utilize o método `cut`, apresentado na aula.

<details>
  <summary>Resposta</summary>

<br/>

```python
df_inativos['Década'] = pd.cut(df_inativos['Ano'], 
                               range(0, 3000, 10),
                               right = True, 
                               include_lowest=True, 
                               labels=range(0, 3000, 10)[:-1])
```

<br/>

</details>

### Transformando Dados com Mapeamento (De/Para)

<pre>Por fim, vamos substituir os nomes das entidades listadas nas colunas <b>OrgN1</b> e <b>OrgN2</b> para as suas respectivas siglas, conforme mapeamento abaixo.</pre>

👉 dica: utilize o método `map`, com o mapeamento <b>de/para</b> sendo feito por meio de dicionário, em que o <b>de</b> é a chave do dicionário e o <b>para</b> é o valor correspondente.

<table>
    <tr>
        <td>
            <table>
                <tr>
                    <th colspan="2">OrgN1</th>
                </tr>
                <tr>
                    <th>Ministério</th>
                    <th>SIGLA</th>
                </tr>
                <tr>
                    <td>MINISTERIO DA SAUDE</td>
                    <td>MS</td>
                </tr>
                <tr>
                    <td>MINISTERIO DA EDUCACAO</td>
                    <td>MEC</td>
                </tr>
                <tr>
                    <td>MINISTERIO DO MEIO AMBIENTE</td>
                    <td>MMA</td>
                </tr>
            </table>
        </td>
        <td>
            <table>
                <tr>
                    <th colspan="2">OrgN2</th>
                </tr>
                <tr>
                    <th>Órgão</th>
                    <th>SIGLA</th>
                </tr>
                <tr>
                    <td>AGENCIA NACIONAL DE SAUDE SUPLEMENTAR</td>
                    <td>ANS</td>
                </tr>
                <tr>
                    <td>FUNDACAO UNIVERSIDADE DE BRASILIA</td>
                    <td>FUB</td>
                </tr>
                <tr>
                    <td>INSTITUTO BRASILEIRO DO MEIO AMBIENTE E DOS RECURSOS NATURAIS RENOVAVEIS</td>
                    <td>IBAMA</td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<details>
  <summary>Resposta</summary>

<br/>

```python
mapeamento_OrgN1 = {'MINISTERIO DA SAUDE':'MS', 
                    'MINISTERIO DA EDUCACAO':'MEC',
                    'MINISTERIO DO MEIO AMBIENTE':'MMA'}

mapeamento_OrgN2 = {'AGENCIA NACIONAL DE SAUDE SUPLEMENTAR': 'ANS',
                    'FUNDACAO UNIVERSIDADE DE BRASILIA': 'FUB',
                    'INSTITUTO BRASILEIRO DO MEIO AMBIENTE E DOS RECURSOS NATURAIS RENOVAVEIS': 'IBAMA'}

df_inativos['OrgN1'] = df_inativos['OrgN1'].map(mapeamento_OrgN1)

df_inativos['OrgN2'] = df_inativos['OrgN2'].map(mapeamento_OrgN2)
```

<br/>

</details>

<pre>Por fim, veja como ficou o resultado final, após o tratamento de dados da base.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
None
```

<br/>

</details>

In [4]:
df_inativos.head()

,Ano,OrgN1,OrgN2,Valor
0,2015,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,540948943
1,2016,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,567996390.2
2,2017,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,AUSENTE
3,2018,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,626216020.1
4,2019,MINISTERIO DA SAUDE,AGENCIA NACIONAL DE SAUDE SUPLEMENTAR,657526821.1

## Reorganização 🗂️ dos Dados 🎲

<pre>A biblioteca Pandas 🐼 permite a leitura de diversos formatos de arquivos, inclusive planilhas Excel, muito utilizadas para o armazenamento e publicação de pequenas bases de dados.</pre>

<pre>A base de <a href="https://ssp.rs.gov.br/indicadores-criminais">indicadores criminais por município e ano do Estado do Rio Grande do Sul</a> é publicada no formato Excel. Execute as duas células abaixo para obter os Indicadores criminais geral e por município do ano de 2024.</pre>

In [5]:
!pip install --upgrade openpyxl --quiet

In [6]:
from bs4 import BeautifulSoup
from requests import get
from urllib.parse import urljoin

base = 'https://www.ssp.rs.gov.br/indicadores-criminais'
html = get(base).content
soup = BeautifulSoup(html, 'html.parser')

# identifica a URL da planilha de 2024 que tem dados de crimes no RS
urls = [urljoin(base, element.get('href')) for element in soup.find_all('a') if element.get('href') and all(substring in element.get('href') for substring in ['geral-e', 'municipio', '-2024'])]

#salva o arquivo no sistema de arquivos
xlsx = get(urls[0])
if xlsx.status_code == 200:
    with open('data/indicadores_criminais_rs_2024.xlsx', mode='wb') as xlsx_file:
        xlsx_file.write(xlsx.content)

<pre>A planilha armazenada em <b>data/indicadores_criminais_rs_2024.xlsx</b> contém dados consolidados na planilha denominada <b>Geral</b> e dados para cada município com periodicidade anual e mensal.</pre>

<img src="figs/indicadores_criminais_rs_2024_geral.png" width="800px" style="margin-left: auto; margin-right: auto;">

<pre>Comece carregando a planilha armazenada em <b>data/indicadores_criminais_rs_2024.xlsx</b>, aba <b>2024</b>, com pandas 🐼, e atribua o resultado à variável <b>df_2024</b>.</pre>

👉 dica: utilize o método `read_excel` do `pandas` e escolha corretamente o valor para o parâmetro `sheet_name`

<details>
  <summary>Resposta</summary>

<br/>

```python
import pandas as pd

df_2024 = pd.read_excel("data/indicadores_criminais_rs_2024.xlsx", sheet_name='2024')
```

<br/>

</details>

<pre>Agora, perceba que o cabeçalho da planilha pode começar em uma linha arbitrária, mas terá <b>Municípios</b> na célula correspondente ao cabeçalho, na primeira coluna.</pre>

<img src="figs/indicadores_criminais_rs_2024_cabecalho.png" width="800px" style="margin-left: auto; margin-right: auto;">

<pre>Identifique o número da linha do DataFrame <b>df_2024</b> que corresponde ao cabeçalho e atribua à variável <b>linha_cabecalho</b>.</pre>

🚨 Futuramente, usaremos essa informação para remover as linhas desnecessárias, acima do cabeçalho, do nosso DataFrame. 🚨

<details>
  <summary>Resposta</summary>

<br/>

```python
linha_cabecalho = df_2024.index[df_2024.iloc[:,0] == 'Municípios'][0]
```

<br/>

</details>

<pre>Igualmente, perceba que os dados de interesse acabam antes da linha que totaliza os números dos municípios, que terá <b>Total RS</b> na célula correspondente à totalização dos municípios, na primeira coluna.</pre>

<img src="figs/indicadores_criminais_rs_2024_rodape.png" width="800px" style="margin-left: auto; margin-right: auto;">

<pre>Identifique o número da linha do DataFrame <b>df_2024</b> que corresponde à totalização dos municípios e atribua à variável <b>linha_total</b>.</pre>

🚨 Futuramente, usaremos essa informação para remover as linhas desnecessárias, a partir da totalização dos municípios, do nosso DataFrame. 🚨

<details>
  <summary>Resposta</summary>

<br/>

```python
linha_total = df_2024.index[df_2024.iloc[:,0] == "Total RS"][0]
```

<br/>

</details>

### Seleção 🍕 e Filtro 🍝 em DataFrame 📽️

<pre>Agora, modifique o nome das colunas do DataFrame <b>df_2024</b> para que correspondam ao cabeçalho da planilha.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_2024.columns = [column.strip() for column in df_2024.iloc[linha_cabecalho,:]]
```

<br/>

</details>

<pre>Utilize a informação dos números das linhas do cabeçalho (<b>linha_cabecalho</b>) e totalização de municípios (<b>linha_total</b>) para que o DataFrame apenas preserve as linhas que incluem os dados dos Municípios do Rio Grande do Sul. Mais precisamente, dados de <b>ACEGUA</b> a <b>XANGRI-LA</b>.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_2024 = df_2024.iloc[linha_cabecalho+1:linha_total]
```

<br/>

</details>

<pre>Agora, adicione uma coluna <b>Ano</b> ao DataFrame <b>df_2024</b> e atribua o valor <b>2024</b> à todas as células dessa coluna.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_2024['Ano'] = 2024
```

<br/>

</details>

<pre>Por fim, use a coluna de <b>Municípios</b> como índice do seu DataFrame <b>df_2024</b>.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_2024 = df_2024.set_index(['Municípios'])
```

<br/>

</details>

<pre>Descubra se há valores ausentes em alguma coluna do DataFrame <b>df_2024</b>.</pre>

<details>
  <summary>Resposta</summary>

<br/>

```python
df_2024.isna().any().any()
```

<br/>

</details>

🚨 Não há valores ausentes no DataFrame em comento. 🚨